URLCrazy v0.5 Released 15 July, 2012

diff --git a/urlcrazy b/urlcrazy
--- a/urlcrazy
+++ b/urlcrazy
@@ -1,4 +1,9 @@
 #!/usr/bin/env ruby
+#
+# URLCrazy
+# (C) Andrew Horton
+#
+#
 require 'rubygems'
 require 'getoptlong'
 require 'singleton'
@@ -23,56 +28,7 @@ require 'tld.rb'
 require 'common-misspellings.rb'
 require 'homophones.rb'
 
-$VERSION="0.4"
-
-=begin
-
-Read the README file
-
-TO DO:
-add multiple output/log formats.
-add reverse resolve
-phonetic spelling
-new typo - subtitution of double/repeated characters. google => giigle
-
-confirm popularity results - -  compare popularity vs. AOL search histories
-
-make gui that shows :
-
-domain __________________ GO
-
-domainname 	typo-type 	typo		popularity	tld	valid  	resolves	whois
-yahoo.com	missing-dot	yahoocom	149,000		-	n	-		AVAILABLE
-dog.co.uk	pluralize	dogs.co.uk	45,000		.co.uk	y	210.2.4.5 [UK]	?
-
-cache/	save results in mysql or text files
-
-let ppl register domains from the gui version
-
-
-
-	
-	double letter -> single letter, vice versa
-	ili => il
-	c => s
-	vowel swap (never start of word)
-	y + > ie
-	ei = > ie
-	
-
-maybe use http://whois.rubyforge.org/rdoc/ for whois info
-maybe use maxmind geoip for countries of IPs -- maybe not as useful coz that's just where it's hosted
-
-Similar but not related are domains that look the same but are different. change l for 1 etc
-
-what this provides that strider doesn't?
-shows potential domain typo popularity
-shows available domain typos that aren't hijacked -- no whois yet
-focused on finding typos more than discovering sites using typos to serve ads
-discovers more classes of typos
-
-
-=end
+$VERSION="0.5"
 
 class Keyboard
 	def initialize(layout)
@@ -91,20 +47,22 @@ class Keyboard
 	def key_left(char)
 		r=row(char)
 		return nil if r.nil?
-		return nil if r.index(char)==0  # already far left
-		r[r.index(char)-1].nil? ? nil : "%c" % r[r.index(char)-1]
+		return nil if r.index(char).nil?
+		return nil if r.index(char)==0  # already far left		
+		r[r.index(char)-1].nil? ? nil : "%c" % r[r.index(char)-1]		
 	end
 	
 	def key_right(char)
 		r=row(char)
 		return nil if r.nil?
+		return nil if r.index(char).nil?
 		return nil if r.index(char)==r.length-1  # already far right
 		r[r.index(char)+1].nil? ? nil : "%c" % r[r.index(char)+1]
 	end
 	
 	def row(char)
 		#returns keyboard. eg. qwertyuiop  or nil if not found
-		r=@rows.map {|k| k if k.include?(char) }.compact.to_s
+		r=@rows.map {|k| k if k.include?(char) }.join
 		r.empty? ? nil : r
 	end
 end
@@ -119,7 +77,7 @@ attr_accessor :type, :name, :valid_name, :tld, :extension, :registered_name, :po
 		@resolved_mx=""
 		return if !@valid_name
 
-		begin 
+		begin
 			@resolved_a=IPSocket.getaddress(@name)
 			rescue
 		end
@@ -132,8 +90,7 @@ attr_accessor :type, :name, :valid_name, :tld, :extension, :registered_name, :po
 
 	
 	def get_popularity
-		# cuil.com is good.
-		# google confuses dots for commas and spaces
+		# Google confuses dots for commas and spaces
 	
 		return "" if !@valid_name
 		begin
@@ -189,6 +146,12 @@ class Domainname
 		self.character_replacement.sort.uniq.each {|c|
 			t=Typo.new
 			t.type ="Character Replacement"
+			t.name=c
+			@typos<< t
+		}
+		self.double_character_replacement.sort.uniq.each {|c|
+			t=Typo.new
+			t.type ="Double Character Replacement"
 			t.name=c
 			@typos<< t
 		}
@@ -248,6 +211,15 @@ class Domainname
 			@typos<< t
 		} 
 
+unless RUBY_VERSION =~ /^1.8/
+		self.homoglyphs.sort.uniq.each {|c|
+			t=Typo.new
+			t.type ="Homoglyphs"
+			t.name=c
+			@typos<< t
+		} 
+end
+
 		self.wrong_tld.sort.uniq.each {|c|
 			t=Typo.new
 			t.type ="Wrong TLD"
@@ -293,14 +265,13 @@ class Domainname
 	def character_replacement
 		kb=$keyboard
 		list=Array.new
-		(0..@domain.length-1).each {|i|
-		
+
+		(0..@domain.length-1).each {|i|		
 			keyleft=kb.key_left(@domain[i..i])
 			if !keyleft.nil?
 				x=@domain.dup
 				x[i]=keyleft
-				list << x
-			
+				list << x			
 			end
 		
 			keyright=kb.key_right(@domain[i..i])
@@ -313,6 +284,35 @@ class Domainname
 		list
 	end
 	
+	def double_character_replacement
+		kb=$keyboard
+		list=Array.new
+
+		(0..@domain.length-1).each {|i|
+			if @domain[i..i] == @domain[i+1..i+1]
+				keyleft=kb.key_left(@domain[i..i])
+				if !keyleft.nil?
+					x=@domain.dup
+					x[i]=keyleft
+					x[i+1]=keyleft
+					list << x			
+				end
+		
+				keyright=kb.key_right(@domain[i..i])
+				if !keyright.nil?
+					x=@domain.dup
+					x[i]=keyright
+					x[i+1]=keyright
+					list << x
+				end
+				next
+			end			
+		}
+		list
+	end
+
+
+
 	def character_insertion
 		kb=$keyboard
 		list=Array.new
@@ -351,7 +351,7 @@ class Domainname
 	
 	
 	def stripdashes
-		@domain.delete("-")
+		[@domain.delete("-")]
 	end
 	
 	
@@ -368,7 +368,7 @@ class Domainname
 	end
 
 
-# unused
+	# unused
 	def popular_sld
 		reg_name = TLD.registered_name(@domain)
 		common_tlds = %w|co.uk com.au co.za |
@@ -409,7 +409,7 @@ class Domainname
 
 		domains=[]
 		@domain.split(//).each_with_index do |c,i| 
-			flipped = masks.map {|mask| (c[0] ^ mask).chr.downcase }.select {|x| x =~ allowed_chars }
+			flipped = masks.map {|mask| (c[0].ord ^ mask).chr.downcase }.select {|x| x =~ allowed_chars }
 			domains << flipped.map {|x| e=@domain.clone; e[i]=x; e }
 		end
 		domains.flatten!.sort!.uniq!
@@ -444,59 +444,126 @@ class Domainname
 	end
 
 	
+	def replace_permutations(string,pattern,replacement)
+		permutations=[]
+		# how many times does pattern appear? it is n
+		n = string.scan(pattern).size
+		# generate perumations map for n times
+		map = [pattern,replacement].repeated_permutation(n).map
+
+		occurances = string.match(pattern)
+		# for each occurance of pattern, replace using the map
+		map.each do |mapset| 
+			#puts mapset.inspect
+			strsplit = string.split(pattern)
+			mapset.each_with_index do |thisreplacement,i|
+				#puts [i,thisreplacement].inspect
+				strsplit[i] = strsplit[i] + thisreplacement
+			end
+			permutations << strsplit.join
+		end
+		permutations.flatten.sort.uniq - [string]
+	end
+
+
+	def homoglyphs
+		#https://en.wikipedia.org/wiki/Homoglyph
+		homoglyphs = {"0"=>"o", "1"=>"l", "l"=> "i", "rn" => "m", "cl"=>"d", "vv"=>"w" }
+		all_homoglyphs = homoglyphs.merge(homoglyphs.invert)
+		list=[]
+		all_homoglyphs.each_pair {|x,y|
+			list << replace_permutations(@domain,x,y)
+		}
+		list.flatten.sort.uniq
+	end
 
 end
 
 
 def usage 
-print "Usage: #{$0} [options] domainname
-URLCrazy generates and tests domainname typo permutations to study typo squatting / URL hijacking.
-URLCrazy version #{$VERSION} by Andrew Horton (urbanadventurer)
-Homepage: http://www.morningstarsecurity.com/research/urlcrazy
+print "URLCrazy version #{$VERSION}
+by Andrew Horton (urbanadventurer)
+http://www.morningstarsecurity.com/research/urlcrazy
 
-Typo types :
-Character Omission, Character Repeat, Adjacent Character Swap, Adjacent Character Replacement,
-Adjacent Character Insertion, Missing Dot, Strip Dashes, Singular or Pluralise, Common Misspellings, 
-Vowel Swaps, Homophones, Bit Flipping (Cosmic Rays), Wrong Top Level Domain, and Wrong Second Level
-Domain.
+Generate and test domain typos and variations to detect and perform typo squatting, URL hijacking,
+phishing, and corporate espionage.
+
+Supports the following domain variations:
+Character omission, character repeat, adjacent character swap, adjacent character replacement, double 
+character replacement, adjacent character insertion, missing dot, strip dashes, singular or pluralise,
+common misspellings, vowel swaps, homophones, bit flipping (cosmic rays), homoglyphs, wrong top level 
+domain, and wrong second level domain.
+
+Usage: #{$0} [options] domain
 
 Options
  -k, --keyboard=LAYOUT	Options are: qwerty, azerty, qwertz, dvorak (default: qwerty)
- -p, --no-popularity	Do not check domain popularity
- -r, --no-resolve	Do not resovle DNS
+ -p, --popularity	Check domain popularity with Google
+ -r, --no-resolve	Do not resolve DNS
  -i, --show-invalid	Show invalid domain names
- -V, --version   	Print version information. This version is #{$VERSION}
+ -f, --format=TYPE	Human readable or CSV (default: human readable)
+ -o, --output=FILE	Output file
+ -h, --help		This help
+ -v, --version   	Print version information. This version is #{$VERSION}
 
 "
+# -R, --only-resolve	Show only domain names that DNS resolve
+if RUBY_VERSION.to_f < 1.9
+	puts "Warning: You are using a Ruby version below 1.9. Some features are not available.\n\n"
+end
 
 end
 
+# send output to the screen, file, or both
+def puts_output(*s)
+	unless s.empty?
+		$output_filep.puts s.first if $output_filep
+		puts s.first
+	else
+		# as puts with no arguments
+		$output_filep.puts if $output_filep
+		puts
+	end
+end
+
+def print_output(s)
+	$output_filep.print s if $output_filep
+	print s
+end
+
+
 
 # -----------------------------------------------------------------
-check_popularity=true
+check_popularity=false
 resolve_domains=true
 show_invalid=false
+show_only_resolve=false
+output_filename=nil
+$output_filep=nil
 keyboard_layout="qwerty"
-
+output_type="human"
 
  opts = GetoptLong.new(
       [ '--help', '-h', GetoptLong::NO_ARGUMENT ],
       [ '--keyboard','-k', GetoptLong::REQUIRED_ARGUMENT ],
       [ '--no-resolve','-r', GetoptLong::NO_ARGUMENT ],
-      [ '--no-popularity','-p', GetoptLong::NO_ARGUMENT ],
+      [ '--popularity','-p', GetoptLong::NO_ARGUMENT ],
       [ '--show-invalid','-i', GetoptLong::NO_ARGUMENT ],
-      [ '-V','--version', GetoptLong::NO_ARGUMENT ]
+      [ '--output','-o', GetoptLong::REQUIRED_ARGUMENT ],
+      [ '--format','-f', GetoptLong::REQUIRED_ARGUMENT ],
+      [ '--only-resolve','-R', GetoptLong::NO_ARGUMENT ],
+      [ '-v','--version', GetoptLong::NO_ARGUMENT ]
     )
 
 begin
  opts.each do |opt, arg|
     case opt
-        when '--help'
+        when '--help','-h'
                 usage
                 exit
         when '--keyboard','-k'
-                if ['qwerty','azerty'].include? arg
-			keyboard_layout=arg
+                if ['qwerty','qwertz','dvorak','azerty'].include? arg.downcase
+			keyboard_layout=arg.downcase
 		else
 			puts "Error: Unknown keyboard layout: #{arg}"
 			exit
@@ -504,12 +571,27 @@ begin
         when '--no-resolve','-r'
                 resolve_domains=false
   	when '--show-invalid','-i'
-                show_invalid=true 
-        when '--no-popularity','-p'
-                check_popularity=false 
+                show_invalid=true
+  	when '--only-resolve','-R'
+                show_only_resolve=true  
+        when '--popularity','-p'
+                check_popularity=true 
+        when '--format','-f'
+                output_type=arg.downcase
+		unless ["human","csv"].include?(output_type)
+			puts "Invalid output type"
+			exit 1
+		end
+        when '--output','-o'
+                output_filename=arg
+		begin
+			$output_filep = File.new(output_filename,"w")			
+		rescue
+			puts "Cannot write to output file, #{output_filename}"
+			exit 1
+		end
         when '-V','--version'
                 puts $VERSION; exit
-
     end
  end
 rescue
@@ -525,37 +607,41 @@ end
 
 $keyboard=Keyboard.new(keyboard_layout)
 
-
 d=Domainname.new(ARGV[0].downcase)
 abort "Aborting. Invalid domainname." unless d.valid == true
 
-puts "URLCrazy Domainname Typo Report"
-puts "For".ljust(10) +": #{d.domain}"
-puts "Keyboard".ljust(10) +": #{keyboard_layout}"
-puts "At".ljust(10) +": #{Time.now}"
-puts
+abort "Aborting. Cannot show only domains that resolve when not resolving domains." if show_only_resolve and not resolve_domains
+
+if output_type=="human"
+	puts_output "URLCrazy Domain Report"
+	puts_output "Domain".ljust(10) +": #{d.domain}"
+	puts_output "Keyboard".ljust(10) +": #{keyboard_layout}"
+	puts_output "At".ljust(10) +": #{Time.now}"
+	puts_output
+end
+
 d.create_typos
 
-
+# output
 columns=Array.new
 widths=Array.new
 
 headings=["Typo Type","Typo","Valid","Pop","DNS-A","DNS-MX","Extn"]
-(0..6).each {|c| columns[c]=Array.new }
+(0..headings.size-1).each {|c| columns[c]=Array.new }
 
 # remove invalid hostnames
 if show_invalid==false
 	d.typos = d.typos.select {|x| x if x.valid_name }
 end
 
-puts "# Please wait. #{d.typos.size} hostnames to process"
+puts_output "# Please wait. #{d.typos.size} hostnames to process" if output_type=="human"
 
 # resolve popularity faster with threads
 threads=[]
 d.typos.each {|typo|
 	threads << Thread.new(typo) {|thistypo|
-		typo.get_resolved if resolve_domains == true 
-		thistypo.get_popularity if check_popularity == true
+		typo.get_resolved if resolve_domains
+		thistypo.get_popularity if check_popularity
 	}
 }
 threads.each {|aThread| aThread.join }
@@ -571,28 +657,44 @@ d.typos.each {|typo|
 		columns[6] << typo.extension.to_s
 }
 
+# trim unneeded columns
 unless show_invalid
-	# remove valid? column
+	headings -= ["Valid"] 
 	columns[2] = nil
-	columns.compact!
-	headings[2] = nil
-	headings.compact!
 end
-# print headings
+unless check_popularity
+	headings -= ["Pop"]
+	columns[3] = nil
+end
+unless resolve_domains
+	headings -= ["DNS-A"] 
+	headings -= ["DNS-MX"]
+	columns[4] =nil
+	columns[5] =nil
+end
+headings.compact!
+columns.compact!
+
+# print report columns
 columns.each_with_index {|column,i|
 	widths[i]=((column.map {|row| row.nil? ? 0 : row.length } << headings[i].length).compact.sort[-1].to_i) + 2
-	print headings[i]
-	print " " * (widths[i] - headings[i].length)
+	print_output headings[i]
+	print_output " " * (widths[i] - headings[i].length) if output_type=="human"
+	print_output "," if output_type=="csv" and i < columns.size-1
 }
-puts
-puts widths.map {|w| "-" *w}.join
+puts_output
+puts_output widths.map {|w| "-" *w}.join if output_type=="human"
 
+# print rows
 columns[0].each_with_index {|row,i|
 	columns.each_with_index {|col,j|
-		print columns[j][i]
-		print " " * (widths[j]-columns[j][i].length)
+		print_output columns[j][i]
+		print_output " " * (widths[j]-columns[j][i].length) if output_type=="human"
+		print_output "," if output_type=="csv" and j < columns.size-1
 	}
-	puts
+	puts_output
 }
-puts
+puts_output
+
+$output_filep.close if $output_filep
 
